-- MySQL Script generated by MySQL Workbench
-- Thu Sep  6 13:02:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zavrsni_rad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zavrsni_rad` ;

-- -----------------------------------------------------
-- Schema zavrsni_rad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zavrsni_rad` DEFAULT CHARACTER SET utf8 ;
USE `zavrsni_rad` ;

-- -----------------------------------------------------
-- Table `zavrsni_rad`.`KORISNIK_ROLA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni_rad`.`KORISNIK_ROLA` ;

CREATE TABLE IF NOT EXISTS `zavrsni_rad`.`KORISNIK_ROLA` (
  `ID_ROLA` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` NVARCHAR(55) NOT NULL,
  `OPIS` NVARCHAR(255) NULL,
  PRIMARY KEY (`ID_ROLA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni_rad`.`KORISNIK_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni_rad`.`KORISNIK_STATUS` ;

CREATE TABLE IF NOT EXISTS `zavrsni_rad`.`KORISNIK_STATUS` (
  `ID_STATUS` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` NVARCHAR(55) NOT NULL,
  `OPIS` NVARCHAR(255) NULL,
  PRIMARY KEY (`ID_STATUS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni_rad`.`KORISNIK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni_rad`.`KORISNIK` ;

CREATE TABLE IF NOT EXISTS `zavrsni_rad`.`KORISNIK` (
  `ID_KORISNIK` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` NVARCHAR(55) NOT NULL,
  `PASSWORD` NVARCHAR(255) NOT NULL,
  `EMAIL` NVARCHAR(255) NOT NULL,
  `POSLEDNJE_LOGOVANJE` DATETIME NULL,
  `ID_ROLA` INT NOT NULL,
  `ID_STATUS` INT NOT NULL,
  PRIMARY KEY (`ID_KORISNIK`),
  INDEX `fk_KORISNIK_KORISNIK_ROLA_idx` (`ID_ROLA` ASC),
  INDEX `fk_KORISNIK_KORISNIK_STATUS1_idx` (`ID_STATUS` ASC),
  CONSTRAINT `fk_KORISNIK_KORISNIK_ROLA`
    FOREIGN KEY (`ID_ROLA`)
    REFERENCES `zavrsni_rad`.`KORISNIK_ROLA` (`ID_ROLA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KORISNIK_KORISNIK_STATUS1`
    FOREIGN KEY (`ID_STATUS`)
    REFERENCES `zavrsni_rad`.`KORISNIK_STATUS` (`ID_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni_rad`.`TIP_ALBUMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni_rad`.`TIP_ALBUMA` ;

CREATE TABLE IF NOT EXISTS `zavrsni_rad`.`TIP_ALBUMA` (
  `ID_TIP_ALBUMA` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` VARCHAR(55) NOT NULL,
  `OPIS` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_TIP_ALBUMA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni_rad`.`ALBUM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni_rad`.`ALBUM` ;

CREATE TABLE IF NOT EXISTS `zavrsni_rad`.`ALBUM` (
  `ID_ALBUMA` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` NVARCHAR(255) NOT NULL,
  `GODINA_IZDAVANJA` NVARCHAR(4) NOT NULL,
  `OMOT` NVARCHAR(255) NOT NULL,
  `ID_TIP_ALBUMA` INT NOT NULL,
  `CENA` SMALLINT NOT NULL,
  PRIMARY KEY (`ID_ALBUMA`),
  INDEX `fk_ALBUM_TIP_ALBUMA1_idx` (`ID_TIP_ALBUMA` ASC),
  CONSTRAINT `fk_ALBUM_TIP_ALBUMA1`
    FOREIGN KEY (`ID_TIP_ALBUMA`)
    REFERENCES `zavrsni_rad`.`TIP_ALBUMA` (`ID_TIP_ALBUMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zavrsni_rad`.`KORISNIK_ALBUM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zavrsni_rad`.`KORISNIK_ALBUM` ;

CREATE TABLE IF NOT EXISTS `zavrsni_rad`.`KORISNIK_ALBUM` (
  `ID_KORISNIK` INT NOT NULL,
  `ID_ALBUMA` INT NOT NULL,
  INDEX `fk_KORISNIK_PROIZVOD_KORISNIK1_idx` (`ID_KORISNIK` ASC),
  INDEX `fk_KORISNIK_ALBUM_ALBUM1_idx` (`ID_ALBUMA` ASC),
  CONSTRAINT `fk_KORISNIK_PROIZVOD_KORISNIK1`
    FOREIGN KEY (`ID_KORISNIK`)
    REFERENCES `zavrsni_rad`.`KORISNIK` (`ID_KORISNIK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KORISNIK_ALBUM_ALBUM1`
    FOREIGN KEY (`ID_ALBUMA`)
    REFERENCES `zavrsni_rad`.`ALBUM` (`ID_ALBUMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO zavrsni_rad.KORISNIK_ROLA
VALUES 
	('1','Administrator', 'Administrator ima prava da dodaje albume i pregleda albume odnosno da menja sadrzaj web aplikacije'),
	('2','Korisnik', 'Korisnik ima prava da pregleda albume i da kupi albume');
    
INSERT INTO zavrsni_rad.KORISNIK_STATUS
VALUES 
	('1','Aktivan','Korisnik je kreiran i aktivan'),
	('2','Blokiran','Korisnik je blokiran');

INSERT INTO zavrsni_rad.TIP_ALBUMA
VALUES 
	('1','Full-album','An Album usually consists of 10-12 songs focusing on one style and usually a theme that the artist decides before hand. To call it an album most people say that it has to be over 25 minutes long.'),
	('2','EP','An EP is an extended play, which is more contains more songs than a single, but less songs than an full-album.EP is defined as a four or more track release with the tracks being of equal importance to one another'),
	('3','Demo','Demos are usually what bands or singer songwriters create themselves using whatever tools they have available.Demos are usually 3-4 songs and consist of a mix of covers and originals.'),
    ('4','Single','Singles usually refer to one song that an artist is releasing. It is usually a part of the album and is released before the album is to gain exposure and a extend the fan base. '),
    ('5','Split','A split album (or split) is a music album which includes tracks by two or more separate artists.Split albums differ from "various artists" compilation albums in that they generally include several tracks of each artist'),
    ('6','Compilation','A compilation album comprises tracks, either previously released or unreleased, usually from several separate recordings by either one or several performers or multiple artists with only one or two tracks each.');